### ISSUE TITLE
Add accessibility test task

### ISSUE THREAD

**Issue by gusliedke** [comicrelief/campaign#1003]

**Comment by pvhee** [comment]
Is this something that is part of our Lighthouse automation in e.g. cr.com? @gusliedke @adamclark-dev

**Comment by adamclark-dev** [comment]
@gusliedke was having a look into how the accessibility tasks in LIghthouse conformed with the AA rating requirements. 

We are currently only failing the Concourse CI task on CR.com if the performance tests fail.
