### ISSUE TITLE
Nav Bugs

### ISSUE THREAD

**Issue by k-pammi** [comicrelief/campaign#1057]
Steps to Reproduce:
Issue 1: Page is moved to complete left when ESU icon is clicked
1. Go to https://pr-1055-7oshkki-tx3mbsqmxtu74.eu.platform.sh
2. Click on the ESU icon, notice the whole page moves to the left and ESU widget moved to the right side on a blank white space
![page doesn t look as expected when esu icon is clicked on the nav](https://user-images.githubusercontent.com/16117926/28163681-16f288f4-67c4-11e7-84f1-fd416ae32bb7.png)

Issue 2:  CR logo doesn't look as expected on IE browsers
1. Go to https://pr-1055-7oshkki-tx3mbsqmxtu74.eu.platform.sh
2. Observe the logo looks too small not as expected on IE 11 browser
3. logo and the Nav menu links are moved to right side of the page not aligned in the center
![logo issue on ie](https://user-images.githubusercontent.com/16117926/28163913-eb70471a-67c4-11e7-8029-f986c65eaf81.png)

Issue 3: Giving page icon tool tip issue
1. Go to https://pr-1055-7oshkki-tx3mbsqmxtu74.eu.platform.sh
2. On the nav, click on the esu icon
3. The esu widget opens, now click on the login to giving page icon
4. The giving page opens in a new tab
5. When you come back to the homepage notice the `login to giving page' tool tip is still left open on the esu widget 
expected: tooltip should be closed as soon as it's clicked
![giving page tooltip issue](https://user-images.githubusercontent.com/16117926/28164679-5e0b82d2-67c8-11e7-842d-737fc35d8bdd.png)
(Note: same issue happens even when just giving page icon is clicked, if you go to the giving page tab and comes back to the nav. Giving page tool tip is still displaying)

Issue 4: Sub items are showing under diff links when hovered 
1. Go to https://pr-1055-7oshkki-tx3mbsqmxtu74.eu.platform.sh/fundraise
2. On IE11 browsers, hover over Fundraise(landing) link and Legal link
3. Notice the sub-item links are showing under another menu item when hovered 
screenshot attached
![sub items are showing under different links](https://user-images.githubusercontent.com/16117926/28168441-04ac0d06-67d7-11e7-8e3b-50e2d5adcb4e.png)

Issue 5: Search is not working on IE11
1. Go to  https://pr-1055-7oshkki-tx3mbsqmxtu74.eu.platform.sh/fundraise
2. Click on the search icon on the nav
3. Notice search block is not showing up 

Issue 6: Tooltip issue when cookie message is left open (not sure if this will be part of this ticket)
1. Go to https://pr-1055-7oshkki-tx3mbsqmxtu74.eu.platform.sh/fundraise
2. Keep the cookie message open
3. Hover over the nav icons, search, login to giving page and ESU
4. Notice the tooltip is covering the icons
![tooltip issue](https://user-images.githubusercontent.com/16117926/28169691-0c8a696a-67db-11e7-9069-b150c920f395.png)

Issue 7: ESU widget is not opening on iPad Pro 9.3 version
On iPad Pro 9.3 landscape
1. Go to https://pr-1055-7oshkki-tx3mbsqmxtu74.eu.platform.sh/fundraise
2. Click on the esu icon
3. Notice esu widget doesn't open when clicked on it

**Comment by Heleen-cr** [comment]
@k-pammi 
Fixed issue 1, 2 and 4
The tooltip issues are known issues caused by the plugin we use.

**Comment by k-pammi** [comment]
@Heleen-cr Issue 1, 2, 4 and 7 are fixed now
Can issue 5 be fixed, it still exists.
Issue 8: On devices, when the esu is clicked the page is scrolls down a bit covering the nav

**Comment by Heleen-cr** [comment]
Issue 5 is an issue we might fix in a separate ticket so it won't hold back the nav work. Also because this issue exists on RND too, so is not something that has slipped in now. 
Issue 8: on devices the scrolling down happens because the keyboard is opened to type something into the input field. This is by design.

**Comment by Heleen-cr** [comment]
@k-pammi issue 5 is solved.

**Comment by Heleen-cr** [comment]
tooltip issue is fixed as well in the comicrelief theme.

**Comment by k-pammi** [comment]
issue 5 and tooltip issue is fixed
@Heleen-cr  can you label this as closed plz
