### ISSUE TITLE
Add iframe sizing script

### ISSUE THREAD

**Issue by adamclark-dev** [comicrelief/campaign#1062]
We need to add a script to the cr_iframe module that will take messages containing height information from the embedded page and will use these to size to the iframe.

**Comment by pradip3271** [comment]
On IE ( 11, Edge 14 & 15 ) iFrame not visible fully. 
![contactusedge15](https://user-images.githubusercontent.com/20820603/28323334-6684c7be-6bd0-11e7-876f-845a8940eab3.png)

**Comment by pradip3271** [comment]
On iPhone iFrame not fit in to the screen once you select different category.
![contactusiframeiphone](https://user-images.githubusercontent.com/20820603/28324665-d5593442-6bd3-11e7-9bf9-50b0d360e8d2.png)
