### ISSUE TITLE
Wrap news article teaser in anchor tag

### ISSUE THREAD

**Issue by Heleen-cr** [comicrelief/campaign#1071]
At the moment news article teasers (as can be found on the news overview landing page and in the related news article section at the bottom of a news article) are not clickable as a whole. Only the title of the article is clickable.
This is also a problem for how we want to track links through GTM. 

- make the whole article teaser 'card' link through to the article.

<img width="683" alt="screen shot 2017-07-18 at 16 30 42" src="https://user-images.githubusercontent.com/21171954/28325830-d0a61804-6bd6-11e7-8f9b-d9d2de933eb3.png">

**Comment by CarolineRennie** [comment]
@Heleen-cr the article filter tracking can be done via the category id in the URL so this ticket should just be to make the entire card/block clickable for the user

**Comment by CarolineRennie** [comment]
@Heleen-cr  as Gus is currently working on news article stuff I've assigned this to him
