### ISSUE TITLE
Email Sign Up campaign field update

### ISSUE THREAD

**Issue by CarolineRennie** [comicrelief/campaign#1112]
On the Red Nose Day website, the email sign up is sending through incorrect campaign field data: 
"campaign" = "campaign" 

This appears to have started from 22/6/2017 and "campaign" = "RND17" stopped on 21/6/2017 for submissions form this site.

This is incorrect and needs to revert back to "campaign" = "RND17" for the rednoesday.com ESU so that we can report on ESUs from correct campaign websites.

**Comment by k-pammi** [comment]
ESU campaign field value showing as expected on RND17 staging, passed QA
