### ISSUE TITLE
Content wall teaser block - if no image - background colour to teaser block

### ISSUE THREAD

**Issue by CarolineRennie** [comicrelief/campaign#1140]
Currently CW with no image is using images of block colour to make them work. If no image is selected, a background colour should be applicable:

![image](https://user-images.githubusercontent.com/23260070/29125589-183f28b0-7d14-11e7-910f-2ce410258f7b.png)

**Comment by AndyEPhipps** [comment]
@alexjohnston266 @CarolineRennie : is this just 'Teaser' blocks ([a la this guy](https://www.comicrelief.com/block/38)), or other blocks too? If so, can you let me know which need this update please?

**Comment by alexjohnston266** [comment]
@AndyEPhipps nope, just teaser!
