### ISSUE TITLE
Cards grid

### ISSUE THREAD

**Issue by gusliedke** [comicrelief/campaign#1157]
https://github.com/comicrelief/pattern-lab/issues/251

**Comment by pradip3271** [comment]
On Firefox browser there is no gap between two card 

![ffbrowsercardsmerge](https://user-images.githubusercontent.com/20820603/29618740-01d0322e-8811-11e7-9519-f3929479d0fe.png)
rows.

**Comment by pradip3271** [comment]
On IE browsers, width left card displays in centre.

![iewidthleft](https://user-images.githubusercontent.com/20820603/29619125-1fcc6c4c-8812-11e7-82f2-921293dcbca7.png)

**Comment by pradip3271** [comment]
On iPad pro (v10.3), width centre card displays on left.

![ipadswidthcentre](https://user-images.githubusercontent.com/20820603/29620553-24515210-8816-11e7-8709-d5991af05d0c.png)

**Comment by pradip3271** [comment]
On iPad pro (ios 10.3), Air (ios 9.3), multiple cards in a row are not same size.

![ipadprocardssize](https://user-images.githubusercontent.com/20820603/29620868-11bac324-8817-11e7-9572-f9bcec812a89.png)

**Comment by pradip3271** [comment]
Issue 1,2 and 4 resolved.
Issue 3  -  not resolved.
      - On iPad pro (ios 10.3), Air (ios 9.3) and Tab 4 (1280x800 px) portrait view - centre card displays on left

**Comment by Heleen-cr** [comment]
@pradip3271 
Ipad issue is fixed. https://pr-1159-q375ivy-tx3mbsqmxtu74.eu.platform.sh/fundraise

**Comment by pradip3271** [comment]
Passed QA, ready for staging.
