### ISSUE TITLE
Video header component review

### ISSUE THREAD

**Issue by CarolineRennie** [comicrelief/campaign#1163]
Ensure that video header component is suitable for our default content rules.
As this was tweaked for the infamous Sara Cox video, please review to make sure component is ready for SR18/all future video headers which should conform to standardised content requirements.

*RULES FOR VIDEO HEADER CONTENT* 
* file size must be no more than 3MB
* recommended duration of video clip is about 10 seconds. It could be longer, but depends on whether you can fit it into the max file size and still have good quality. 
* central content of the video is the focal point - when the browser/screen size is changed the video will be cropped accordingly therefore the video should work within from 320px to 2560px (based on most used screen sizes from RND17)
* camera shot must be steady / movement should be controlled 

@Heleen-cr  please add to this!

**Comment by Heleen-cr** [comment]
I've had a look at the video background in campaign and this is actually fine. The specific Sara Cox overrides were done in an older version of PL and apparently we've changed things back to focus on the centre of the video again.
This means that if the latest campaign release is pulled into any of our themes the video background should work as we want.

**Comment by CarolineRennie** [comment]
@Heleen-cr as agreed rather than keeping the RND17 version, we will just remove the video header from Sara Cox page and make sure that our content gathering teams always have 1 rule for how the videos should work.
