### ISSUE TITLE
update single msg background img styles

### ISSUE THREAD

**Issue by Heleen-cr** [comicrelief/campaign#1173]
currently the image style used is large 1700 x 450, this should be updated to be 1700 x 500. 

See https://github.com/comicrelief/pattern-lab/issues/250

### test notes:
- go to https://pr-1174-3hxt5wy-tx3mbsqmxtu74.eu.platform.sh/fundraise
- check the image styles used for the background image single message row:
   - for the large breakpoint (1024px) the image should be cropped and scaled to 1700x500px
   - the medium and small breakpoints remain the same as they were (768x450px)

**Comment by pradip3271** [comment]
Passed QA, ready to deploy.
