### ISSUE TITLE
Integrate automated semantic versioning

### ISSUE THREAD

**Issue by pvhee** [comicrelief/campaign#1189]
We should start doing automatic releases using semver, much like we're doing in https://github.com/comicrelief/pattern-lab. Basically, every commit to `develop` (or `master`, as we can/should kill `develop`) will generate a new release automatically.

**Comment by Saphyel** [comment]
In pattern-lab we are using https://github.com/semantic-release/semantic-release that generates releases in npm & github, semver unfortunately only calculates versions... maybe we should do more research on here?
