### ISSUE TITLE
Remove padding option across all components

### ISSUE THREAD

**Issue by CarolineRennie** [comicrelief/campaign#1221]
As a default, each component has padding above and below it to separate it from other components. 
Single message row has the options for Remove and Negative padding:
"Remove padding" will remove the selected padding of the component. "Negative padding" will remove the selected padding of the component as well as the corresponding padding of the component above or below."

If we allow the remove function on all component types, then we would not necessarily need the negative padding option (which always seemed a little hacky).

**Comment by gusliedke** [comment]
@CarolineRennie maybe assign it some else to pick up next?!
