### ISSUE TITLE
Change search result icons to transparent icons

### ISSUE THREAD

**Issue by Heleen-cr** [comicrelief/campaign#1280]
The icons on the search result page for downloadable, video and pages items have a red background in the image. As this colour varies in our sub themes it would be better to have the white icon on a transparent background and set the background colour via css on the image's container. 

- change icons for transparent versions
- set the correct background colour via css in each theme

**Comment by CarolineRennie** [comment]
http://vignette1.wikia.nocookie.net/jurassicpark/images/5/53/Raptor_-_Clever_Girl.gif/revision/latest?cb=20140408111011
