### ISSUE TITLE
Titles not be displayed properly in search

### ISSUE THREAD

**Issue by adamclark-dev** [comicrelief/campaign#1281]
Page titles are being displayed badly in search, padding is also broken at points. 

See https://www.comicrelief.com/search?text=grants

![image](https://user-images.githubusercontent.com/9998404/32793045-c2aa10dc-c95c-11e7-987f-94457b86ed96.png)
![image](https://user-images.githubusercontent.com/9998404/32793070-d59cb0c8-c95c-11e7-98f8-968817b2efb3.png)

**Comment by pvhee** [comment]
@adamclark-dev those items that you see are unpublished pages. If you redo that search as a logged out user, you should see the following correct result:

![screencapture-comicrelief-search-1510680375591](https://user-images.githubusercontent.com/119355/32794556-18336f54-c961-11e7-9940-a498f070770b.png)
