### ISSUE TITLE
Remove develop branch

### ISSUE THREAD

**Issue by adamclark-dev** [comicrelief/campaign#1288]
There appears to no longer be any use for the develop branch now that we are using releases.

We should remove the develop branch and merge the contents into master.

cc/ @pvhee @Saphyel

**Comment by pvhee** [comment]
@adamclark-dev agreed, this is also very much related to https://github.com/comicrelief/campaign/issues/1189 (and I believe we should set up automatic semver before we kill the `develop` branch)

**Comment by Saphyel** [comment]
closed by @adamclark-dev ?
