### ISSUE TITLE
Create "news editor" role

### ISSUE THREAD

**Issue by pvhee** [comicrelief/campaign#1309]
This new role could have the following permissions:

* News article: Create new content
* News article: Delete own content
* News article: Edit any content
* News article: Edit own content
* News article: View revisions

and would not have the following permissions:

* News article: Delete revisions
* News article: Delete any content
* News article: Revert revisions

**Comment by pvhee** [comment]
@CarolineRennie would this be a useful addition to our user permission system?

**Comment by CarolineRennie** [comment]
Specifically  create articles only rather than any content? 
Though would images be required to be added at media entities first or are they added to the article directly into the template?

**Comment by pvhee** [comment]
Great questions.. we probably need to give them access to create/edit media entities as well if that's used often for news articles. @alexjohnston266 ?

**Comment by Saphyel** [comment]
@CarolineRennie I think is more common create landing pages?

**Comment by pvhee** [comment]
@Saphyel could you link up this ticket to the release of this within SR? So we make sure we're QA'ing this when it goes up to production.

**Comment by Saphyel** [comment]
@pvhee yes, it will be part of the release, thanks.

**Comment by CarolineRennie** [comment]
@Saphyel - this is not functioning as expected - Media Team with news editor roles are able to access all content to edit

**Comment by Saphyel** [comment]
The requirement was access only to news... access to all content will be a new requirement...

**Comment by CarolineRennie** [comment]
@Saphyel - yes, but the users are able to access all content and edit all content so it is not functioning?

**Comment by pvhee** [comment]
@CarolineRennie that is incorrect, they can see all content but can only add or edit news articles. It's expected behaviour for them to see all content because anonymous users can also see all content so there is no obvious way to distinguish, unless we were to build news editor a separate dashboard which only lists news articles. But that's new functionality.

**Comment by CarolineRennie** [comment]
Yep, egg on my face. The reason is that the media team also had reviewer permission so they could see all content but can only edit articles. Sincerest apologies.

**Comment by pvhee** [comment]
No probs :) Permissions are a bit complicated and easy to make mistakes with. Also will review our test coverage on this. \cc @Saphyel
