### ISSUE TITLE
Update focal_point config

### ISSUE THREAD

**Issue by Saphyel** [comicrelief/campaign#1338]
We are using the normal styles effects but in order to use focal point we need to migrate them to the new styles:

focal point crop
focal point scale and crop

**Comment by AndyEPhipps** [comment]
Okay, so I've been through the [documented implementation](https://www.ostraining.com/blog/drupal/focal-point/) of this on a brand new content type, with a brand new Focal Point (/ And Crop) image style and it **still** doesn't work.

Our content types are definitely using the image styles; you can still edit these existing Focal Point image styles, updating the crop sizing and see the change, but still no focal point option.

Perhaps we need to look to the Focal Point and/or Crop API module as a source of this problem 

FAO: @CarolineRennie @pvhee @Saphyel

**Comment by AndyEPhipps** [comment]
AHA, got it- looks like we've got the wrong widget selected for the Form Display, will see if I can sort this in Campaign
