### ISSUE TITLE
Update Campaign build to use Yarn not NPM

### ISSUE THREAD

**Issue by AndyEPhipps** [comicrelief/campaign#1343]
Aiming to speed up the build process by using Yarn over NPM

**Comment by AndyEPhipps** [comment]
_(copy-pasted from the PR):_

Okay, since SR18 is currently using the NPM-flavoured version of Campaign (and the build is failing), I think this needs to be merged in first.

QA-able **[here](https://pr-1344-kdldkqq-tx3mbsqmxtu74.eu.platform.sh/)**, need need to compare with the current master build **[here](https://develop-tx3mbsqmxtu74.eu.platform.sh/fundraise)**

**Comment by VenuBotla** [comment]
Styling looks fine. Passed QA.

**Comment by VenuBotla** [comment]
Assigning back to @AndyEPhipps for release
