### ISSUE TITLE
Add CTA description as optional field to content wall 

### ISSUE THREAD

**Issue by CarolineRennie** [comicrelief/campaign#1377]
Add a CTA description field so that screen readers can pick up additional descriptions of links when the CTA Text is not sufficiently descriptive enough.

Part of https://github.com/comicrelief/sr18/issues/216 

Acceptance criteria:
- [x] Additional field in the CMS for adding description to CTA (optional field) 
- [x] When description is added, screen reader should read the additional description 
- [ ] When no description is added, the screen reader should read that the link in internal / opens in new tab

**Comment by pradip3271** [comment]
Screen reader not read out the cta title.

**Comment by Saphyel** [comment]
@pradip3271 should be fix now, sorry
