### ISSUE TITLE
Add structured data to all CR websites or apps 

### ISSUE THREAD

**Issue by phiral** [comicrelief/campaign#1419]
At the moment we are not using any rich or structured formats for search engines to display certain type of content in appealing format for user engagement.

We could provide explicit clues about the meaning of a page to Google by including structured data on the page. Structured data is a standardized format for providing information about a page and classifying the page content; for example, on a recipe page, what are the ingredients, the cooking time and temperature, the calories, and so on.

Google uses structured data that it finds on the web to understand the content of the page, as well as to gather information about the web and the world in general. For example, here is a JSON-LD structured data snippet that might appear on the contact page of the Unlimited Ball Bearings corporation, describing their contact information:

`<script type="application/ld+json">
{
  "@context": "http://schema.org",
  "@type": "Organization",
  "url": "http://www.example.com",
  "name": "Unlimited Ball Bearings Corp.",
  "contactPoint": {
    "@type": "ContactPoint",
    "telephone": "+1-401-555-1212",
    "contactType": "Customer service"
  }
}
</script>`

Please review the following documentation on the following link  on how we could apply structure data for our content:

**Introduction to Structured Data**
https://developers.google.com/search/docs/guides/intro-structured-data

**Mark Up Content Items**
https://developers.google.com/search/docs/guides/mark-up-content

**Comment by adamclark-dev** [comment]
@phiral can you break this down into,

- the individual sites that you want structured data in
- the components that you want structured data on
- examples of the structured data that you want

Can you then create tickets in the relevant repositories.

**Comment by phiral** [comment]
Add JSON-LD structured data for the following content types:

**Apply this across all Drupal environments (CR.COM, SR.COM)**

**Enhancements**

Breadcrumb
https://developers.google.com/search/docs/data-types/breadcrumb

Carousels
https://developers.google.com/search/docs/guides/mark-up-listings

Logo
https://developers.google.com/search/docs/data-types/logo

Sitelinks Searchbox
https://developers.google.com/search/docs/data-types/sitelinks-searchbox

**Content types**

Article
https://developers.google.com/search/docs/data-types/article

Event
https://developers.google.com/search/docs/data-types/event

Recipe
https://developers.google.com/search/docs/data-types/recipe


Video
https://developers.google.com/search/docs/data-types/video

Speakable (optional)
https://developers.google.com/search/docs/data-types/speakable

Podcast
https://developers.google.com/search/docs/data-types/podcast

Product (Shop)
https://developers.google.com/search/docs/data-types/product

**Comment by phiral** [comment]
This has been done part of the new CR website updates and migration to Contentful.
