### ISSUE TITLE
News article filters on news page doesn't work

### ISSUE THREAD

**Issue by CarolineRennie** [comicrelief/campaign#1420]
When a user filters the news page, the articles should only be displayed from that category. Currently this functionality is not working on any of our websites.

![image](https://user-images.githubusercontent.com/23260070/40663007-b4329384-634f-11e8-8cd6-02449b31758c.png)

**Comment by k-pammi** [comment]
1. Currently the articles are not displayed when I select another category from the default `All` on page 1. But when I go to page 2 in the pagination and try to select another category then those respective articles are displayed for the category I selected. 
2. When I come back and select `All` category, now it displays all the articles related to All and when I try to select another category again staying on ALL category and on page 1, it seems to be working(i.e selected category articles are displayed)

**Comment by pradip3271** [comment]
Passed QA.
