### ISSUE TITLE
Fix Sitemap XML for Search Crawler on RND.com

### ISSUE THREAD

**Issue by phiral** [comicrelief/campaign#1423]
I've just noticed the sitemap xml that is dynamically generated is not being generated correctly.
This needs to be fixed urgently as this file is used by all search engines to index our website urls.he 

See > **https://www.rednoseday.com/sitemap.xml**

At the moment I can see this happening on RND.com. However should check the other websites to make sure. 

These look to be generating ok:
https://www.comicrelief.com/sitemap.xml
https://www.sportrelief.com/sitemap.xml

**Comment by phiral** [comment]
@adamclark-dev any ETA on this? I know there's talk about merging RND.COM with CR.COM so if this is the case please confirm and close this.

**Comment by pvhee** [comment]
Let's wait until we have a decision on rnd.com / cr.com @phiral ? \cc @CarolineRennie to be prioritised right after

**Comment by adamclark-dev** [comment]
@phiral for future reference, can you create tickets in the individual site repos if an issue only occurs on one site. As campaign applies to all three sites and is also public.

Have added ticket to RND repo and closing this one,

https://github.com/comicrelief/rnd17/issues/388
