### ISSUE TITLE
Facebook Tracking Pixel - Marketing 

### ISSUE THREAD

**Issue by phiral** [comicrelief/campaign#1450]
Our marketing team have requested for the following snippet to be added all our websites:

Needs to be auctioned by 14 or 15th November latest:

- www.comicrelief.com 
- shop.comicrelief.com
- donation.comicrelief.com
- payin.comicrelief.com

I'm able to set this up and implement this via Google Tag Manager (GTM), please can someone review and get back to me whether this is ok to be auctioned on GTM.  

```<!-- Facebook Pixel Code -->
<script>!function(e,t,n,o,c,a,f){e.fbq||(c=e.fbq=function(){c.callMethod?c.callMethod.apply(c,arguments):c.queue.push(arguments)},e._fbq||(e._fbq=c),(c.push=c).loaded=!0,c.version="2.0",c.queue=[],(a=t.createElement(n)).async=!0,a.src="https://connect.facebook.net/en_US/fbevents.js",(f=t.getElementsByTagName(n)[0]).parentNode.insertBefore(a,f))}(window,document,"script"),fbq("init","445034839357835"),fbq("track","PageView");</script>
<noscript><img height="1" width="1" src="https://www.facebook.com/tr?id=445034839357835&ev=PageView&noscript=1"/></noscript>
<!-- End Facebook Pixel Code -->```

**Comment by adamclark-dev** [comment]
Fine by me, we should discuss whether we keep it live on NOTV nearer the time.

**Comment by phiral** [comment]
Cool cheers @adamclark-dev. We can disable this anytime if required.
