### ISSUE TITLE
CR JustGiving - Google Search Console Varification 

### ISSUE THREAD

**Issue by phiral** [comicrelief/campaign#1468]
Add the verification for fundraise.comicrelief.com using DNS config method:

google-site-verification=Y9BpLCHLX6fPLHTu83kFfRp7Ny3axgh7AKqwGQWy2-I

**Comment by AndyEPhipps** [comment]
I'm not sure if this still needs doing @phiral, but fundraise.comicrelief.com isn't our product; this'll need to be passed onto the JustGiving peoples

**Comment by phiral** [comment]
@AndyEPhipps fro, what I know fundraise.comicrelief.com is our custom set up on JG platform. This is similar to the Frost journey we use to have. We therefore own the domain for this. 

Do you know if we manage the sub-domain for this? If so Adam usually did the verification set up by updating the DNS settings.

**Comment by phiral** [comment]
Closing this as it's an old ticket and been actioned
