### ISSUE TITLE
email is saving "null" on school phase message after validation

### ISSUE THREAD

**Issue by KrupaPammi** [comicrelief/campaign#1491]
Clicking on submit before selecting a school phase option is saving email feld with null value, when option is selected and then clicked on submit is still not saving the email but saves null.

**Comment by AndyEPhipps** [comment]
I thought you said the data was going into the tables ok?

**Comment by KrupaPammi** [comment]
> I thought you said the data was going into the tables ok?
> 
> When the school phase isn't set yet, and we click the button, is it actually submitting the form?

@AndyEPhipps I checked this in the DB this morning and could not see any `null` values in any email fields when I tested on the PR envt for both CR and SR, assuming this issue happened only after it deployed to staging and MQ started giving alerts to @corinja with email as null.

**Comment by AndyEPhipps** [comment]
I could actually see the issue locally and have figured out what the problem was; will sort out a test page this morning for you 👍

**Comment by AndyEPhipps** [comment]
https://pr-1492-s3t36ta-tx3mbsqmxtu74.eu.platform.sh/test/esu - already have the test page here

I'll set-up PRs for SR and CR now as I'd imagine it'd easier to test the database entries?

**Comment by KrupaPammi** [comment]
> https://pr-1492-s3t36ta-tx3mbsqmxtu74.eu.platform.sh/test/esu - already have the test page here
Messages aren't going into the queue testing on this envt

> I'll set-up PRs for SR and CR now as I'd imagine it'd easier to test the database entries?
Thanks! yeah this will be easy to test, sorry for the hassle
