### ISSUE TITLE
Tracking Updates Required on CR.COM and SR.COM for Emarsys

### ISSUE THREAD

**Issue by phiral** [comicrelief/campaign#1500]
Can we please implement the dataLayer in the file below:

The main requirement for this capturing the email address in the '**userEmail**' field whenever someone enters their email address in a form on the website e.g. Email signups (ESU) or contact us or other forms. Once available can we make this available and propagate globally site-wide on each page or URL type.

See following for instructions:
[CR.com-and-SR.com_Global-Tracking-Instructions_20190716.txt](https://github.com/comicrelief/campaign/files/3626825/CR.com-and-SR.com_Global-Tracking-Instructions_20190716.txt)

For information on why this is required please review the following Emarsys documentation:
https://help.emarsys.com/hc/en-us/articles/360005884453-identifying-users-with-web-extend

**Comment by AndyEPhipps** [comment]
@phiral , the current implementation relates to the _Drupal_ users, i.e, dev and content team:

![Screen Shot 2019-09-26 at 13 04 22](https://user-images.githubusercontent.com/4737220/65686823-314a2080-e05e-11e9-806c-a3ab21381c60.png)

```
The new updates:
	'user': {
		  'id': 'user123456',				//optional if available - registered user id
		  'loggedIn': 'Y',				//optional if available - Y or N
		  'userEmail': 'examplename@somedomain.com'	//required - set defualt value to 'N' and populate the email when it becomes available in the CR.COM user journey and propagate it site wide
									
		}
	}];

```
 somehow adds a 'userEmail' in that, which doesn't really make any sense, if we're trying to capture **visitor** data.

When you say _'populate the email'_ , do you mean pre-populate any other email fields on site with one already supplied to an ESU.? And/or populate that DL 'userEmail' field in the DL object?

**Comment by phiral** [comment]
@AndyEPhipps to confirm on this:

We require a solution where we update the dataLayer ( **'userEmail': 'examplename@somedomain.com'**) when a user makes their email address available when submitting a form on the website (ESU's, Marketing Preference and ContactUs ...etc).

**Comment by phiral** [comment]
Done
