### ISSUE TITLE
Core and module updates

### ISSUE THREAD

**Issue by AndyEPhipps** [comicrelief/campaign#1501]

**Comment by AndyEPhipps** [comment]
QA-able here https://pr-1502-mrdesuy-tx3mbsqmxtu74.eu.platform.sh/fundraise

Should be identical to master env (https://master-tx3mbsqmxtu74.eu.platform.sh/fundraise), I've been doing some content changes and haven't noticed anything different.

**Comment by KrupaPammi** [comment]
> Hi @KrupaPammi, the updates are QA-able here https://pr-1502-mrdesuy-tx3mbsqmxtu74.eu.platform.sh/fundraise
> 
> Should be identical to master env (https://master-tx3mbsqmxtu74.eu.platform.sh/fundraise), I've been doing some content changes and haven't noticed anything different.

Have tested this, on search page I typed 'test' and not seeing any results where as master env is giving results. Other than that all good.

**Comment by AndyEPhipps** [comment]
Seems to be working okay now, maybe the content was still being indexed?
