### ISSUE TITLE
Add Tag dropdown to editor library view

### ISSUE THREAD

**Issue by CarolineRennie** [comicrelief/campaign#866]
Editors currently can apply a few different actions to many of the same content via the editor library view drop down (see [admin list](https://develop-tx3mbsqmxtu74.eu.platform.sh/admin/content))

We need to review what is currently on this list - but one request is that applying tags could be an action which can be done from the library view rather than having to open each article and apply individually (image to be provided by content team).

<img width="964" alt="content___site-install" src="https://cloud.githubusercontent.com/assets/119355/25907586/bccbafe6-359f-11e7-8555-4c1bb0a15c9a.png">

**Comment by adamclark-dev** [comment]
This was de-scoped as there is currently no easy way to implement this. The need for it was also only 60 articles and an update hook to set all current articles as news was sufficent.
