### ISSUE TITLE
Intermittent bug: CMS adding new content wall row replicating previous row

### ISSUE THREAD

**Issue by CarolineRennie** [comicrelief/campaign#989]
When CMS user adds new content wall row, it will intermittently replicates the previous row.

Intermittent issues. Typically this will happen if user does not save and adds more than one row at a time - especially likely to happen if there is a video in the content wall.

**Comment by pvhee** [comment]
This might be fixed with https://github.com/comicrelief/campaign/issues/1037. Closing for now, until we can replicate this.
