### ISSUE TITLE
Fail Travis build if Drupal install fails

### ISSUE THREAD

**Issue by pvhee** [comicrelief/campaign#997]
We have a dangerous line in our Travis installation at https://github.com/comicrelief/campaign/blob/develop/.travis.yml#L23

```
docker-compose exec web composer campaign:build || true
```

This will lead to success even if the build fails, and mask errors afterwards. This was evidenced by https://travis-ci.com/comicrelief/campaign/builds/48633766 which should have failed at the install step, however, it failed at a later step.

Can we remove the `|| true` to make this fail properly?

**Comment by Saphyel** [comment]
I created this PR: https://github.com/drupal-composer/drupal-scaffold/pull/66 but I'll try to work on the "Provide drupal:scaffold command"

**Comment by adamclark-dev** [comment]
This has been completed a while ago, closing.
